// Code generated by ent, DO NOT EDIT.

package role

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kimsehyoung/dongle/app/auth/ent/authgen/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int32) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int32) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int32) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int32) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int32) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int32) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int32) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int32) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int32) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldID, id))
}

// MemberType applies equality check predicate on the "member_type" field. It's identical to MemberTypeEQ.
func MemberType(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldMemberType, v))
}

// MemberTypeEQ applies the EQ predicate on the "member_type" field.
func MemberTypeEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldEQ(FieldMemberType, v))
}

// MemberTypeNEQ applies the NEQ predicate on the "member_type" field.
func MemberTypeNEQ(v string) predicate.Role {
	return predicate.Role(sql.FieldNEQ(FieldMemberType, v))
}

// MemberTypeIn applies the In predicate on the "member_type" field.
func MemberTypeIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldIn(FieldMemberType, vs...))
}

// MemberTypeNotIn applies the NotIn predicate on the "member_type" field.
func MemberTypeNotIn(vs ...string) predicate.Role {
	return predicate.Role(sql.FieldNotIn(FieldMemberType, vs...))
}

// MemberTypeGT applies the GT predicate on the "member_type" field.
func MemberTypeGT(v string) predicate.Role {
	return predicate.Role(sql.FieldGT(FieldMemberType, v))
}

// MemberTypeGTE applies the GTE predicate on the "member_type" field.
func MemberTypeGTE(v string) predicate.Role {
	return predicate.Role(sql.FieldGTE(FieldMemberType, v))
}

// MemberTypeLT applies the LT predicate on the "member_type" field.
func MemberTypeLT(v string) predicate.Role {
	return predicate.Role(sql.FieldLT(FieldMemberType, v))
}

// MemberTypeLTE applies the LTE predicate on the "member_type" field.
func MemberTypeLTE(v string) predicate.Role {
	return predicate.Role(sql.FieldLTE(FieldMemberType, v))
}

// MemberTypeContains applies the Contains predicate on the "member_type" field.
func MemberTypeContains(v string) predicate.Role {
	return predicate.Role(sql.FieldContains(FieldMemberType, v))
}

// MemberTypeHasPrefix applies the HasPrefix predicate on the "member_type" field.
func MemberTypeHasPrefix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasPrefix(FieldMemberType, v))
}

// MemberTypeHasSuffix applies the HasSuffix predicate on the "member_type" field.
func MemberTypeHasSuffix(v string) predicate.Role {
	return predicate.Role(sql.FieldHasSuffix(FieldMemberType, v))
}

// MemberTypeEqualFold applies the EqualFold predicate on the "member_type" field.
func MemberTypeEqualFold(v string) predicate.Role {
	return predicate.Role(sql.FieldEqualFold(FieldMemberType, v))
}

// MemberTypeContainsFold applies the ContainsFold predicate on the "member_type" field.
func MemberTypeContainsFold(v string) predicate.Role {
	return predicate.Role(sql.FieldContainsFold(FieldMemberType, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Role) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Role) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Role) predicate.Role {
	return predicate.Role(func(s *sql.Selector) {
		p(s.Not())
	})
}
