// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Subtitle is the predicate function for subtitle builders.
type Subtitle func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
