// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SubtitleColumns holds the columns for the "subtitle" table.
	SubtitleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "language", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(16)"}},
		{Name: "url", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "video_id", Type: field.TypeInt},
	}
	// SubtitleTable holds the schema information for the "subtitle" table.
	SubtitleTable = &schema.Table{
		Name:       "subtitle",
		Columns:    SubtitleColumns,
		PrimaryKey: []*schema.Column{SubtitleColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subtitle_video_subtitles",
				Columns:    []*schema.Column{SubtitleColumns[4]},
				RefColumns: []*schema.Column{VideoColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VideoColumns holds the columns for the "video" table.
	VideoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "title", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(32)"}},
		{Name: "url", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
	}
	// VideoTable holds the schema information for the "video" table.
	VideoTable = &schema.Table{
		Name:       "video",
		Columns:    VideoColumns,
		PrimaryKey: []*schema.Column{VideoColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "video_account_id_title",
				Unique:  true,
				Columns: []*schema.Column{VideoColumns[1], VideoColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SubtitleTable,
		VideoTable,
	}
)

func init() {
	SubtitleTable.ForeignKeys[0].RefTable = VideoTable
	SubtitleTable.Annotation = &entsql.Annotation{
		Table: "subtitle",
	}
	VideoTable.Annotation = &entsql.Annotation{
		Table: "video",
	}
}
