// Code generated by ent, DO NOT EDIT.

package subtitlegen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kimsehyoung/dongle/app/subtitle/ent/subtitlegen/predicate"
	"github.com/kimsehyoung/dongle/app/subtitle/ent/subtitlegen/subtitle"
)

// SubtitleDelete is the builder for deleting a Subtitle entity.
type SubtitleDelete struct {
	config
	hooks    []Hook
	mutation *SubtitleMutation
}

// Where appends a list predicates to the SubtitleDelete builder.
func (sd *SubtitleDelete) Where(ps ...predicate.Subtitle) *SubtitleDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SubtitleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SubtitleDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SubtitleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subtitle.Table, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SubtitleDeleteOne is the builder for deleting a single Subtitle entity.
type SubtitleDeleteOne struct {
	sd *SubtitleDelete
}

// Where appends a list predicates to the SubtitleDelete builder.
func (sdo *SubtitleDeleteOne) Where(ps ...predicate.Subtitle) *SubtitleDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SubtitleDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subtitle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SubtitleDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
