// Code generated by ent, DO NOT EDIT.

package videodbgen

import (
	"time"

	"github.com/kimsehyoung/dongle/app/video/ent/schema"
	"github.com/kimsehyoung/dongle/app/video/ent/videodbgen/originalvideo"
	"github.com/kimsehyoung/dongle/app/video/ent/videodbgen/subtitledvideo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	originalvideoFields := schema.OriginalVideo{}.Fields()
	_ = originalvideoFields
	// originalvideoDescCreatedAt is the schema descriptor for created_at field.
	originalvideoDescCreatedAt := originalvideoFields[3].Descriptor()
	// originalvideo.DefaultCreatedAt holds the default value on creation for the created_at field.
	originalvideo.DefaultCreatedAt = originalvideoDescCreatedAt.Default.(time.Time)
	subtitledvideoFields := schema.SubtitledVideo{}.Fields()
	_ = subtitledvideoFields
	// subtitledvideoDescCreatedAt is the schema descriptor for created_at field.
	subtitledvideoDescCreatedAt := subtitledvideoFields[2].Descriptor()
	// subtitledvideo.DefaultCreatedAt holds the default value on creation for the created_at field.
	subtitledvideo.DefaultCreatedAt = subtitledvideoDescCreatedAt.Default.(time.Time)
}
