// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(320)"}},
		{Name: "hashed_password", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(32)"}},
		{Name: "phone_number", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(32)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "role_id", Type: field.TypeInt},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_role_accounts",
				Columns:    []*schema.Column{AccountColumns[6]},
				RefColumns: []*schema.Column{RoleColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RoleColumns holds the columns for the "role" table.
	RoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(16)"}},
	}
	// RoleTable holds the schema information for the "role" table.
	RoleTable = &schema.Table{
		Name:       "role",
		Columns:    RoleColumns,
		PrimaryKey: []*schema.Column{RoleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		RoleTable,
	}
)

func init() {
	AccountTable.ForeignKeys[0].RefTable = RoleTable
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	RoleTable.Annotation = &entsql.Annotation{
		Table: "role",
	}
}
