swagger: "2.0"
info:
  title: Dongle video service
  description: desc
  version: "0.0"
tags:
  - name: Video
host: __API_BASE_URL__
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/video/subtitle:
    post:
      operationId: Video_SubtitleVideo
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/videoSubtitleVideoRequest'
      tags:
        - Video
  /videos:
    get:
      operationId: Video_ListVideos
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/videoListVideosResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: category
          description: '{"all"}'
          in: query
          required: false
          type: string
        - name: pageSize
          in: query
          required: false
          type: integer
          format: int32
        - name: page
          in: query
          required: false
          type: integer
          format: int32
      tags:
        - Video
    delete:
      operationId: Video_DeleteVideo
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: title
          in: query
          required: false
          type: string
      tags:
        - Video
    post:
      operationId: Video_UploadVideo
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/videoUploadVideoRequest'
      tags:
        - Video
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  videoListVideosResponse:
    type: object
    properties:
      videos:
        type: array
        items:
          type: object
          $ref: '#/definitions/videoOriginalVideo'
      nextPage:
        type: integer
        format: int32
  videoOriginalVideo:
    type: object
    properties:
      title:
        type: string
  videoSubtitleVideoRequest:
    type: object
    properties:
      videoId:
        type: string
  videoUploadVideoRequest:
    type: object
    properties:
      title:
        type: string
      data:
        type: string
        format: byte
securityDefinitions:
  bearer:
    type: apiKey
    description: 'Authentication token, prefixed by Bearer: Bearer <token>'
    name: Authorization
    in: header
security:
  - bearer: []
