// Code generated by ent, DO NOT EDIT.

package subtitledvideo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kimsehyoung/dongle/app/video/ent/videodbgen/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLTE(FieldID, id))
}

// OriginalVideoID applies equality check predicate on the "original_video_id" field. It's identical to OriginalVideoIDEQ.
func OriginalVideoID(v int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldOriginalVideoID, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldCreatedAt, v))
}

// OriginalVideoIDEQ applies the EQ predicate on the "original_video_id" field.
func OriginalVideoIDEQ(v int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldOriginalVideoID, v))
}

// OriginalVideoIDNEQ applies the NEQ predicate on the "original_video_id" field.
func OriginalVideoIDNEQ(v int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNEQ(FieldOriginalVideoID, v))
}

// OriginalVideoIDIn applies the In predicate on the "original_video_id" field.
func OriginalVideoIDIn(vs ...int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldIn(FieldOriginalVideoID, vs...))
}

// OriginalVideoIDNotIn applies the NotIn predicate on the "original_video_id" field.
func OriginalVideoIDNotIn(vs ...int) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNotIn(FieldOriginalVideoID, vs...))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldContainsFold(FieldURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOriginalVideo applies the HasEdge predicate on the "original_video" edge.
func HasOriginalVideo() predicate.SubtitledVideo {
	return predicate.SubtitledVideo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OriginalVideoTable, OriginalVideoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOriginalVideoWith applies the HasEdge predicate on the "original_video" edge with a given conditions (other predicates).
func HasOriginalVideoWith(preds ...predicate.OriginalVideo) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(func(s *sql.Selector) {
		step := newOriginalVideoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubtitledVideo) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubtitledVideo) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubtitledVideo) predicate.SubtitledVideo {
	return predicate.SubtitledVideo(func(s *sql.Selector) {
		p(s.Not())
	})
}
