// Code generated by ent, DO NOT EDIT.

package originalvideo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the originalvideo type in the database.
	Label = "original_video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSubtitledVideos holds the string denoting the subtitled_videos edge name in mutations.
	EdgeSubtitledVideos = "subtitled_videos"
	// Table holds the table name of the originalvideo in the database.
	Table = "original_video"
	// SubtitledVideosTable is the table that holds the subtitled_videos relation/edge.
	SubtitledVideosTable = "subtitled_video"
	// SubtitledVideosInverseTable is the table name for the SubtitledVideo entity.
	// It exists in this package in order to avoid circular dependency with the "subtitledvideo" package.
	SubtitledVideosInverseTable = "subtitled_video"
	// SubtitledVideosColumn is the table column denoting the subtitled_videos relation/edge.
	SubtitledVideosColumn = "original_video_id"
)

// Columns holds all SQL columns for originalvideo fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldTitle,
	FieldURL,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
)

// OrderOption defines the ordering options for the OriginalVideo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySubtitledVideosCount orders the results by subtitled_videos count.
func BySubtitledVideosCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubtitledVideosStep(), opts...)
	}
}

// BySubtitledVideos orders the results by subtitled_videos terms.
func BySubtitledVideos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubtitledVideosStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSubtitledVideosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubtitledVideosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubtitledVideosTable, SubtitledVideosColumn),
	)
}
