// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OriginalVideo is the predicate function for originalvideo builders.
type OriginalVideo func(*sql.Selector)

// SubtitledVideo is the predicate function for subtitledvideo builders.
type SubtitledVideo func(*sql.Selector)
